### PR TITLE
only write jsonnnet files if we made changes

### LINKED ISSUE #11: Don't change/modify jsonnetfile.json jsonnetfile.lock.json if there is nothing to do
When running `jb install` on a given project multiple times with no changes, both the `change` as well as `modify` file timestamp of `jsonnetfile.json` and `jsonnetfile.lock.json` are changed. The content as well as meta-data of these files stay the same.

**How to reproduce**:

```bash
stat jsonnetfile.json jsonnetfile.lock.json
jb install
stat jsonnetfile.json jsonnetfile.lock.json
```

**Why would this be needed**:

GNU Make uses timestamps of a recipes prerequisites in order to determine whether to rebuild the given target or not. Given `jsonnetfile.json` and `jsonnetfile.lock.json` as prerequisites and `jb install` as the recipe, the target will always be rebuild if `jsonnetfile.json` and `jsonnetfile.lock.json` change on every execution.

### PR DESCRIPTION
**Pull request by davidovich**
Adding a dep, or updating a dependency version makes writes to the
jsonnet files.

We evaluate the changes on each of the files. An empty jsonnetfile.json
does not create a corresponding lockfile, as a missing lockfile is not
different from its previous (non existent) state.

closes #11

### CODE REVIEW

File: cmd/jb/install.go [hunk 1]
```diff
@@ -58,18 +59,23 @@ func installCommand(dir, jsonnetHome string, uris []string) int {
...
 	locked, err := pkg.Ensure(jsonnetFile, jsonnetHome, lockFile.Dependencies)
 	kingpin.FatalIfError(err, "failed to install packages")
 
-	kingpin.FatalIfError(
-		writeJSONFile(filepath.Join(dir, jsonnetfile.File), jsonnetFile),
-		"updating jsonnetfile.json")
-	kingpin.FatalIfError(
-		writeJSONFile(filepath.Join(dir, jsonnetfile.LockFile), spec.JsonnetFile{Dependencies: locked}),
-		"updating jsonnetfile.lock.json")
+	if depsChanged {
```
Comment (sh0rez) [inline cmd/jb/install.go]: I feel this is too naive, especially because it could miss cases where we need to write although we have not passed any URIs.

For example when running `jb install` without any arguments, this would prevent it from writing the lockfile.

A more robust implementation would be to use a sth like the following:
```go
func checkJsonnetfile(path string, jf *jsonnetFile) bool {
  b := open(path)
  orig := unmarshal(b)

  return deepEqual(orig, jf)
}

Wouldn't say that this is overengineered, rather just a robust solution. Probably better to check twice here than not enough, as it could break a lot of things
```

Comment (sh0rez) [reply cmd/jb/install.go]: And check both files separately :D

**Comment by davidovich** [comment]
I think that opening and reading the file twice is a bad practice and is sometimes brittle on Windows filesystem: the less you do with files the merrier :-). 

As a compromise, I have factored out the diffing and writing as you suggested. Bonus, added tests for the diff function. WDYT?

File: cmd/jb/install_test.go [hunk 2]
```diff
@@ -35,10 +36,9 @@ func TestInstallCommand(t *testing.T) {
 		ExpectedJsonnetLockFile []byte
 	}{
 		{
-			Name:                    "NoURLs",
-			ExpectedCode:            0,
-			ExpectedJsonnetFile:     []byte(`{"dependencies":null}`),
-			ExpectedJsonnetLockFile: []byte(`{"dependencies":null}`),
```
Comment (sh0rez) [inline cmd/jb/install_test.go]: Why don't we expect a lockfile anymore? Shouldn't this yield a empty lockfile as well?

File: pkg/jsonnetfile/jsonnetfile.go [hunk 3]
```diff
@@ -33,13 +33,21 @@ var ErrNoFile = errors.New("no jsonnetfile")
...
-		return m, err
+		return spec.New(), err
 	}
 
+	return UnmarshalBytes(bytes)
+}
+
+// UnmarshalBytes creates a spec.JsonnetFile from bytes. Empty bytes
+// will create an empty spec.
+func UnmarshalBytes(bytes []byte) (spec.JsonnetFile, error) {
```
Comment (sh0rez) [inline pkg/jsonnetfile/jsonnetfile.go]: Very nitpicky: Either `Unmarshal` or `UnmarshaJSON`. The `Bytes` suffix doesn't really include what those bytes are about so either omit it (assume json is common enough) or state that it is JSON, which is always bytes :D

File: cmd/jb/install_test.go (hunk 2 above)
Comment (davidovich) [reply cmd/jb/install_test.go]: I understand that the [current intention of the install command](https://github.com/jsonnet-bundler/jsonnet-bundler/blob/4de4096004cc1c403a13358356d32598063bdc77/cmd/jb/install.go#L40-L43) was to work even if the lockfile is missing. As we ignored the error of [Load()](https://github.com/jsonnet-bundler/jsonnet-bundler/blob/4de4096004cc1c403a13358356d32598063bdc77/pkg/jsonnetfile/jsonnetfile.go#L38-L41), this would initialize an empty lockfile.
Before this change, this empty lockfile was written unconditionally by the installCommand. Now that we write only if there is a diff, there is no diff between empty value lockfile and default value, so no lockfile is written. 

If we were to warrant an empty lockfile (alongside the empty jsonnetfile), I think we should add it in the `initCommand`.

File: pkg/jsonnetfile/jsonnetfile.go (hunk 3 above)
Comment (davidovich) [reply pkg/jsonnetfile/jsonnetfile.go]: Alright.

File: cmd/jb/install_test.go (hunk 2 above)
Comment (sh0rez) [reply cmd/jb/install_test.go]: I‘m fine with this 😃

**Comment by chancez** [comment]
As far as I can tell, this PR broke `jb`, at least with some dependencies like https://github.com/ksonnet/ksonnet-lib/. 

On the latest master:

```
~/p/poetry czibolski ❯❯❯ jb install github.com/ksonnet/ksonnet-lib/ksonnet.beta.4/k.libsonnet
Cloning into 'vendor/.tmp/jsonnetpkg-k.libsonnet-master812140101'...
remote: Enumerating objects: 5, done.
remote: Counting objects: 100% (5/5), done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 2505 (delta 0), reused 3 (delta 0), pack-reused 2500
Receiving objects: 100% (2505/2505), 2.48 MiB | 5.75 MiB/s, done.
Resolving deltas: 100% (933/933), done.
Already on 'master'
Your branch is up to date with 'origin/master'.
>>> Installed k.libsonnet version master
jb: error: failed to install: stat vendor/k.libsonnet/jsonnetfile.lock.json: not a directory
```

I mentioned this to @brancz in the k8s slack when I hit the issue and I looked at recent commits touching the area of code producing the error I see and checked out the commit before this (7fc7c31856f96b7215796e7126e6a5f3303b7214) and the issue is gone.

Running the same `jb install` as above using my locally build `jb` from commit 7fc7c31856f96b7215796e7126e6a5f3303b7214:
```
~/p/poetry czibolski ❯❯❯ /Users/czibolski/projects/jsonnet-bundler/_output/darwin/amd64/jb install github.com/ksonnet/ksonnet-lib/ksonnet.beta.4/k8s.libsonnet                                                   ⏎
GET https://github.com/ksonnet/ksonnet-lib/archive/0d2f82676817bbf9e4acf6495b2090205f323b9f.tar.gz 200
CLEAN vendor/k.libsonnet
```

**Comment by brancz** [comment]
Installing single files was never intended to work, it was purely a coincidence that that ever worked. I talked to @sh0rez already about this, and I was under the impression that the tanka guides etc would be adapted to just install the ksonnet-lib package. It might be that he wanted to implement github style imports first though.

**Comment by metalmatze** [comment]
I would say let's just go with Go style imports and have qualified import paths so that we can be sure that everyone using jsonnet-bundler ends up with the same import paths, cause right now it's a big mess.

**Comment by sh0rez** [comment]
> I would say let's just go with Go style imports and have qualified import paths so that we can be sure that everyone using jsonnet-bundler ends up with the same import paths, cause right now it's a big mess.

I totally agree for all but one library: `k.libsonnet`. The issue here is that this library is kind of global and must probably stay this way. The Kubernetes API schema is evolving over time, so a k.libsonnet generated for a specific version will not fit for all ... only some versions around, unpredictable how long.
So the user must choose which one to use.
**Important** to mention is that the import path must be **unversioned** – third party libraries using `k.libsonnet` must be able to specify "give me the k.libsonnet that fits" – and at the moment this is done by importing it as a global file.

Over at Tanka, we are currently trying out how good the following works:
* At `tk init`, we create a `k.libsonnet` file in the `lib/` folder (not `vendor/`)
* `ksonnet.beta.4` is installed using jb as part of `tk init`
* This file contains the single line `import "ksonnet.beta.4/k.libsonnet`, which will soon change to something like `pkg.tanka.dev/kubernetes/v1.16.libsonnet`, as soon we start maintaining the library.

The benefit of this approach is that it is dead simple, requires no changes to current codebases and has an  authoritative file which states the exact version – effectively an import alias. This also plays well with go-style imports.

WDYT?

**Alternative considered:** Using git tagging of a library called somewhat `prefix/k.libsonnet` – main issues with this approach:
* requires changes to old code
* hard to maintain from a library perspective – with the other approach all kubernetes versions could live in the same folder, git tagging would be able to mark changes to the library (patches, fixes, etc.) instead of version numbers  we don't control

**Comment by brancz** [comment]
I don't believe ksonnet-lib is any different it's a dependency just like any other and I don't think we should be treating it any different. I want it to be upgraded explicitly and I want to explicitly choose a version. Past upgrades of ksonnet-lib versions showed that this is not as transparent as we believe it is, plus that would basically lock us into a state where we can effectively never change anything.

I think tanka doing the import alias would be a perfectly legitimate thing to do, while still aligning with the overall architecture and not making ksonnet-lib any special as a package, I like that approach the best I think.

**Comment by sh0rez** [comment]
Yeah, you‘re right there. Reading again what I wrote above, the first sentence does not really make sense. 

We can easily publish k.libsonnet as a valid jb package and use the alias file to create the required „pseudo-global“ feeling required for use in downstream libraries.
