### PR TITLE
fix: Git ssh-scp syntax

### LINKED ISSUE #67: ssh: Could not resolve hostname
Broken in master:
```
$ rm -rf *
$ GO111MODULE="on" go get github.com/jsonnet-bundler/jsonnet-bundler/cmd/jb@master
go: finding github.com master
go: finding github.com/jsonnet-bundler/jsonnet-bundler master
go: finding github.com/jsonnet-bundler/jsonnet-bundler/cmd master
go: finding github.com/jsonnet-bundler/jsonnet-bundler/cmd/jb master
go: finding github.com/jsonnet-bundler master
$ jb --version
v0.2.1-0.20200124070234-7b8a7836a495
$ jb init
$ jb install git+ssh://git@github.com:hangxie/kustomize-libsonnet.git@test-branch
Initialized empty Git repository in /home/xiehang/tmp/jb/vendor/.tmp/jsonnetpkg-github.com-hangxie-kustomize-libsonnet-test-branch532767166/.git/
ssh: Could not resolve hostname github.com:hangxie: Name or service not known
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
ssh: Could not resolve hostname github.com:hangxie: Name or service not known
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
jb: error: failed to install packages: downloading: exit status 128
```

Things worked with 0.2.0:
```
$ rm -rf *
$ GO111MODULE="on" go get github.com/jsonnet-bundler/jsonnet-bundler/cmd/jb
$ jb --version
v0.2.0
$ jb init
$ jb install git+ssh://git@github.com:hangxie/kustomize-libsonnet.git@test-branch
Initialized empty Git repository in /home/xiehang/tmp/jb/vendor/.tmp/jsonnetpkg-kustomize-libsonnet-test-branch247024765/.git/
remote: Enumerating objects: 11, done.
remote: Counting objects: 100% (11/11), done.
remote: Compressing objects: 100% (11/11), done.
remote: Total 11 (delta 0), reused 7 (delta 0), pack-reused 0
Unpacking objects: 100% (11/11), done.
From github.com:hangxie/kustomize-libsonnet
 * branch            test-branch -> FETCH_HEAD
 * [new tag]         test-tag    -> test-tag
 * [new branch]      test-branch -> origin/test-branch
Branch 'test-branch' set up to track remote branch 'test-branch' from 'origin'.
Switched to a new branch 'test-branch'
```

### PR DESCRIPTION
**Pull request by sh0rez**
- fixes the ssh:// syntax
- adds proper support for scp style (`git@github.com:user/repo.git`, note no `ssh://` and the colon)

The tests were extended to properly cover this.

The scp syntax is internally rewritten to the SSH one, so there won't be any confusion around this

Fixes #67

### CODE REVIEW

File: spec/deps/git_test.go [hunk 1]
```diff
@@ -42,26 +54,28 @@ func TestParseGit(t *testing.T) {
...
-				Version: "v1",
-				Source: Source{GitSource: &Git{
-					Scheme: GitSchemeSSH,
-					Host:   "my.host",
-					User:   "user",
-					Repo:   "repo",
-					Subdir: "/foobar",
-				}},
-			},
-			wantRemote: "ssh://git@my.host:user/repo.git",
```
Comment (cyriltovena) [inline spec/deps/git_test.go]: Should you keep a non github test ?

Comment (metalmatze) [reply spec/deps/git_test.go]: Yes. For sure. I use it with a privately hosted gitea.io instance for example. GitLab might not even be as unpopular.
