### PR TITLE
Replace ETag SHA1 assumption with an explicit call to git ls-remote

### LINKED ISSUE #46: Github ETag doesn't seem to provide the sha1 anymore
The tar file download optimization seems to be broken:

```
GET https://github.com/kubernetes-monitoring/kubernetes-mixin/archive/6a0450b32a0f3b25299dcca7f40157e21c50d023.tar.gz 200
archive install failed: etag value "W/"4c236536ad4b8b15f4daa7ceddac1960d016a60b1f39c3e21d83eada0cc71081"" does not look like a SHA1
retrying with git...
...
```

#38 added an optimization to download a tar from the github server. This optim uses the [Etag](https://github.com/jsonnet-bundler/jsonnet-bundler/pull/38/files#diff-f3708aa6fdbaa2ed2eb6897499e0941fR62-R65) to resolve the sha1 of the dependency. Since it seems that github is no longer returning the sha in it's Etag, the optimisation is broken.

As we know the sha1 once it is downloaded (first through a slower git operation), we could use this info to re-enable the optimisation (on locked dependency). 

We can also use the github api to [resolve the ref](https://developer.github.com/v3/git/refs/?#git-references) (but this is rate-limited to [60 req/hour/incoming IP](https://developer.github.com/v3/#rate-limiting)).

### PR DESCRIPTION
**Pull request by bgagnon**
Not using an undocumented ETag header from the GitHub archive API is
probably for the best. This is slightly slower due to extra round-trip,
but it is still much faster than cloning the repository to resolve the
ref.

Fixes #46

### CODE REVIEW

**Comment by bgagnon** [comment]
@davidovich can you have a look please? thanks!

File: pkg/git.go [hunk 1]
```diff
@@ -171,11 +172,22 @@ func (p *GitPackage) Install(ctx context.Context, name, dir, version string) (st
...
 	isGitHubRemote, err := regexp.MatchString(`^(https|ssh)://github\.com/.+$`, p.Source.Remote)
 	if isGitHubRemote {
-		archiveUrl := fmt.Sprintf("%s/archive/%s.tar.gz", p.Source.Remote, version)
+		// Let git ls-remote decide if "version" is a ref or a SHA1 in the unlikely
+		// but possible event that a ref is exactly 40 hex characters
+		commitSha, err := remoteResolveRef(ctx, p.Source.Remote, version)
+
+		// If the ref resolution failed and "version" looks like a SHA1, assume it is one
+		// and proceed.
+		commitShaPattern, _ := regexp.Compile("^([0-9a-f]{40})$")
```
Comment (davidovich) [inline pkg/git.go]: As you want to ignore the error, you can use:
```suggestion
		commitShaPattern := regexp.MustCompile("^([0-9a-f]{40})$")
```

Comment (davidovich) [reply pkg/git.go]: Again, this is not sha256 compatible, can we relax this regex ? `version` is computed from: 
* the lock file
* provided by the user ([validated from liberal regexps](https://github.com/jsonnet-bundler/jsonnet-bundle)).

File: pkg/git.go [hunk 2]
```diff
@@ -45,47 +45,33 @@ func NewGitPackage(source *spec.GitSource) Interface {
...
-		return "", errors.New(fmt.Sprintf("unexpected status code %d", resp.StatusCode))
-	}
-
-	// GitHub conveniently uses the commit SHA1 at the ETag
-	// signature for the archive. This is needed when doing `jb update`
-	// to resolve a ref (ie. "master") to a commit SHA1 for the lock file
-	etagValue := resp.Header.Get(http.CanonicalHeaderKey("ETag"))
-	if etagValue == "" {
-		return "", errors.New("ETag header is missing from response")
+		return errors.New(fmt.Sprintf("unexpected status code %d", resp.StatusCode))
```
[the remark this answers is not in the document]
Comment (metalmatze) [reply pkg/git.go]: I think that's `fmt.Errorf` but yes, I agree :+1:

File: pkg/git.go [hunk 3]
```diff
@@ -157,6 +143,21 @@ func gzipUntar(dst string, r io.Reader, subDir string) error {
...
+	b := bytes.NewBuffer(nil)
+	cmd := exec.CommandContext(ctx, "git", "ls-remote", "--heads", "--tags", "--refs", "--quiet", remote, ref)
+	cmd.Stdin = os.Stdin
+	cmd.Stdout = b
+	cmd.Stderr = os.Stderr
+	err := cmd.Run()
+	if err != nil {
+		return "", err
+	}
+	commitShaPattern, _ := regexp.Compile("^([0-9a-f]{40})\\b")
```
[the remark this answers is not in the document]
Comment (metalmatze) [reply pkg/git.go]: So `strings.Split(" xyz ", " ")`? :+1:

File: pkg/git.go [hunk 4]
```diff
@@ -157,6 +143,21 @@ func gzipUntar(dst string, r io.Reader, subDir string) error {
 	}
 }
 
+func remoteResolveRef(ctx context.Context, remote string, ref string) (string, error) {
+	b := bytes.NewBuffer(nil)
```
[the remark this answers is not in the document]
Comment (metalmatze) [reply pkg/git.go]: And  then maybe even use `var b *bytes.Buffer`?

**Comment by metalmatze** [comment]
Thanks for working on that.
Yesterday something changed, right? All of sudden the e-tag doesn't work anymore and I thought it was just me until I saw it break on a different machine too. :grin:

File: pkg/git.go (hunk 1 above)
Comment (bgagnon) [reply pkg/git.go]: > this is not sha256 compatible

Which version of git and which repository supports sha256 today?

Comment (davidovich) [reply pkg/git.go]: As you delegate to Git for this, I see an opportunity to not encode the implementation detail. But maybe this is too early.

**Comment by bgagnon** [comment]
@metalmatze yeah, GitHub changed their etag signatures overnight. They don't document these things, so it's my kind of my fault for abusing this header in the first place. Thankfully the git fallback in jb kept things working (but slower).

File: pkg/git.go (hunk 3 above)
[the remark this answers is not in the document]
Comment (bgagnon) [reply pkg/git.go]: Not having any git tooling or repository that supports sha256 makes this hard to test, but I think we can compromise on `^([0-9a-f]{40,})\\b`, so _at least 40 hexa characters_. This is compatible with sha1, sha256 (whenever that is a reality) and sha512 or future hexadecimal hash functions.

File: pkg/git.go (hunk 1 above)
Comment (bgagnon) [reply pkg/git.go]: My understanding is that Git plumbing commands (such as this one) were designed for their output to be parsed and used for scripting. Assuming the sha256 transition plan changes this plumbing command to output a longer sha but keep everything else the same, we can relax the parsing.
